# Component Info
info:
  component: SpringConfig-Server

# HTTP Server
server:
  port: 8887

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jmangialomini/Spring.Cloud.Config.Server

  # Spring properties
  profiles:
    active: dev